### PR TITLE
M-XT3URBK, M-XT3DRBK, M-XT4DRBK

### PR DESCRIPTION
**Pull request by shiiba-cba**

### CODE REVIEW

**Comment by jfedor2** [comment]
Are you sure that all these devices have the same HID report descriptor as the Elecom Huge?

I don't have access to any of those trackballs, but I found some information on the web:

It seems that M_XT3DRBK **does** have the same report descriptor as the Huge (https://www.reddit.com/r/Trackballs/comments/7p8m5y/so_i_got_an_elecom_xt3_today_and_ive_got_a/dsfrzbb/).

It seems that M_DPT1MRBK **does not** have the same report descriptor as the Huge (https://www.reddit.com/r/Trackballs/comments/7vqraz/calling_for_elecom_exg_and_deft_trackball_owners/e09l242/).

I haven't been able to find any information about the EX-G wired or the EX-G PRO.

**Comment by shiiba-cba** [comment]
I will capture and recheck the USB HID Report Descriptor for each model later.

**Comment by shiiba-cba** [comment]
EX-G PRO (Wireless) worked with both HUGE's USB HID Descriptor and EX-G PRO's Descriptor. If you prefer to use HUGE Descriptor, please comment so we can revert the source.

**Comment by jfedor2** [comment]
No, no, what I mean is that the EX-G PRO wireless descriptor isn't broken so it doesn't need a fix. It should already work with an unmodified version.

The problem with the Huge and others is that they have 8 buttons in reality, but only 5 buttons in the descriptor. As far as I can tell the EX-G PRO wireless has 8 buttons in reality and 8 buttons in the descriptor so it should work fine as is.

**Comment by jfedor2** [comment]
Thank you for the contribution!

**Pull request merged**
